title: Sreaperr's Security Notes
description: Writeups y apuntes de ciberseguridad
theme: jekyll-theme-slate

collections:
  writeups:
    output: true
    permalink: /writeups/:path/
  notes:
    output: true
    permalink: /apuntes/:path/

defaults:
  - scope:
      path: ""
      type: writeups
    values:
      layout: default
  - scope:
      path: ""
      type: notes
    values:
      layout: default

show_excerpts: false
