title: sreaperr's Writeups
description: Writeups de máquinas de hacking (DockerLabs, HTB, etc.)
theme: jekyll-theme-slate

collections:
  writeups:
    output: true
    permalink: /writeups/:path/

defaults:
  - scope:
      path: ""
      type: writeups
    values:
      layout: page

show_excerpts: false
